datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
jpa.default.properties.hibernate.hbm2ddl.auto: update

#datasources:
#  default:
#    url: jdbc:postgresql://localhost:5432/carros?currentSchema=carros_test
#    driverClassName: org.postgresql.Driver